env_key:
  - wx250s

dr_percent_below: 1.0
dr_percent_above: 1.0
dr_do_on_reset: False
dr_do_on_N_step: 0
dr_do_at_creation: False


### OBTAINED FROM MULTIENV CONFIG ###

device: cuda
num_env: 100 #00
max_episode_length: 1000
last_action: True