### HIGH-LEVEL ###

device: cuda
env_seed: -1  # no seed if env_seed == -1 else env_seed

eval_freq: 5_000_000
num_eval_steps: 500
do_eval_video: True

### PROPAGATES DOWN TO ENVS IN CODE ###
last_action: True
num_env: 1
max_episode_length: 1000


